### PR TITLE
Enable PLY optimisations in various places

### PR DESCRIPTION
**Pull request by Smattr**
These commits enable PLY's optimisations for the grammar's lexer and parser, and add an option for optimisation of the final grammar.

I'm not sure if you have strong feelings about how or if these optimisations should be enabled. If you want these commits to be refactored or have objections, please let me know. Thanks for your impressive work on plyplus!

### CODE REVIEW

**Comment by erezsh** [comment]
Hi, thank you very much! I'd be interested to learn in what project do you use plyplus, and in what way.

Regarding the patch, I'm a bit worried about losing debug information, and the possibility of introducing a subtle bug regarding the lexer mtab when updating the grammar.
More importantly, I tried running both master and your branch, and got the exact same run speeds. Could you please include example that demonstrates the speed gain?

**Comment by Smattr** [comment]
I maintain a component platform, [CAmkES](https://sel4.systems/CAmkES/), that has a code generator built using PLY. While this works well, the PLY parser imposes a significant maintenance overhead and is a barrier for new people becoming familiar with the code base. I'm in the process of replacing the parser with something built on plyplus. Some of our users currently run Python with optimisations enabled (`-O`) which we handle by passing the relevant arguments to yacc and lex. I was looking to do the same with plyplus.

On closer inspection, I'm not so sure my proposed change is a good idea. I completely agree with you about losing mtab information and would have actually made this conditional on debug if a variable like `DEBUG` in grammar_parser.py existed.

I haven't looked at PLY's source code and I'm not sure whether these options actually enable any internal optimisations. Rather, they let you run with Python's optimiser enabled. The PLY docs imply that this flag does nothing to lex and yacc beyond caching the compiled grammar on disk.

I tested these changes on one of my machines, but now on a different one I can't even get the test suite to pass with optimisations enabled (different PLY versions?). The errors are quite strange and look as if lex is actually failing to tokenise strings correctly. This is when passing `optimize=True` always when constructing `Grammar`s in the test cases. I can make it pass by leaving everything as is, but never passing `optimize=1` to `lex.lex`. This is with PLY version 3.4-3ubuntu2.

This leads me to suspect that perhaps PLY's optimised mode is not as robust as I had thought. I'd be inclined to close and abandon this pull request for now, unless you disagree? Sorry for taking up your time with this.

**Comment by erezsh** [comment]
Generally I would like to enable whatever optimization possible, but this patch adds to complexity (although a tiny bit) and it's unclear if there is any advantage to it.
So I'm okay with closing it, but I'm also okay with leaving it in case someone else wants to give it a try.

And if you care about speed in any way, I strongly suggest that you use pypy :)

P.S. I'm thinking of starting a "projects using plyplus" section. Would it be okay if I add your project to that list?

**Comment by Smattr** [comment]
OK, I can leave it open for now and we can pick this up in the future if it looks like it will make a noticeable speed up.

We experimented with PyPy, and this is still available as a CAmkES build option, but all the test cases we ran at the time actually performed _slower_ under PyPy. This surprised me as I thought the conventional wisdom was everything ran faster under PyPy, unless you were spending most of your time in C, which we are certainly not. I didn't investigate further at the time because there was other more low hanging fruit in terms of optimisation opportunities.

I'd love to have CAmkES listed here! However, the current public version is still built on PLY. I'll let you know when we've moved across the plyplus, though it might be a few months.

**Comment by kirbyfan64** [comment]
@Smattr What version of PyPy were you using?

**Comment by Smattr** [comment]
I don't remember offhand, sorry. This would have been about a year ago. It's possible the situation has changed since then.

**Comment by kirbyfan64** [comment]
@Smattr I know PyPy can seriously make programs faster. Running Sake on a large set of files under CPython takes a bit over 7 seconds; PyPy takes about 0.6 seconds.

**Comment by Smattr** [comment]
To clarify my original comment, I am not saying PyPy is slower than CPython. I too have seen dramatic speed ups with PyPy, but not in the case of CAmkES. I suspect there was some unusual characteristic of our workload at the time. As I said, the situation may be different now.

**Comment by erezsh** [comment]
@Smattr Yes, please let me know when it's done!

Regarding pypy, the slowdown might be caused by the JIT warm-up, if you are running a new process repeatedly on relatively small input chunks. If that is the case, then aggregating all of the parsing to a single process (either by preparation, or by using a server process) might make a significant difference.

**Comment by Smattr** [comment]
Returning to this, I'm still inclined to close this PR for insufficient robustness. In the end, I implemented a [ccache](https://ccache.samba.org/)-style wrapper for our code generator that dramatically improves perceived response times, so applying PLY optimisations is no longer a priority for us. Unfortunately it is still the case that none of this is public, but I'll drop a pointer to it when it is.

**Comment by erezsh** [comment]
I've closed this PR. Feel free to re-open a similar one in the future if you deem it relevant.

**Comment by Smattr** [comment]
Sorry it took so long, but the plyplus-based version of CAmkES is finally public. It's available in the 'next' branch of https://github.com/seL4/camkes-tool/tree/next. Thanks for your excellent work on plyplus.

To clarify some of the above discussion about PyPy, our code generator is relatively short running so I think you're right that the JIT warm-up dominates the execution, which is why we don't see a speed up when using it over CPython. The problem we face is that our users are running this as part of a long build involving some GCC invocations. Their natural instinct is to compare the CAmkES generator with GCC (a heavily optimised C program) which inevitably leads to CAmkES coming off second best. The ccache-like wrapper I referred to above mitigates this by easily beating both GCC and ccache, which seems to have stemmed user complaints.

**Pull request closed without merging**
